
import R3 from '../assets/student-profile.png'

export const ResultsTermData = [

    {
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
        id:0,
        pic:R3,
        name:'Sarah James Johnson Smith',
        subject:'Mathematics',
        welcomeTest:15,
        midTermTest:20,
        overall:40,
   },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         welcomeTest:15,
         midTermTest:20,
         overall:40,
    },
    
]