
import R3 from '../assets/student-profile.png'

export const ResultsExamsData = [

    {
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
        id:0,
        pic:R3,
        name:'Sarah James Johnson Smith',
        subject:'Mathematics',
        tts:15,
        project:20,
        onlineExam:0,
        exam:40,
        overall:40,
   },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
        id:0,
        pic:R3,
        name:'Sarah James Johnson Smith',
        subject:'Mathematics',
        tts:15,
        project:20,
        onlineExam:0,
        exam:40,
        overall:40,
   },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },{
         id:0,
         pic:R3,
         name:'Sarah James Johnson Smith',
         subject:'Mathematics',
         tts:15,
         project:20,
         onlineExam:0,
         exam:40,
         overall:40,
    },
]